spring:
  application:
    name: sheep
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

server:
  port: 8888
  servlet:
    context-path: /api

app:
  jwt:
    secret: ecqN4N4aD6ToTXEEJlVgjPZqCo0tp6Q4+b4g/HI/TyYg/YQKl66BvvWLxJLecc+dJ1bJRZCOKwOtyuSuXkqBQw==
    age: 120000
  cookie:
    name: pid
    age: 120