POST {{host}}/api/register
Content-Type: application/json

{
  "group": "pim-241",
  "username": "ivan",
  "password": "asdf"
}

###
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "ivan",
  "password": "asdf"
}